//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;


namespace XettuyenDGNLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int ID { get; set; }
      
        
        public string Username { get; set; }
        
        public string Password { get; set; }
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$",ErrorMessage = "Nhập đúng định dạng email.")]
        public string Email { get; set; }
        [Phone(ErrorMessage ="Chỉ nhập số")]
        [MaxLength(10,ErrorMessage ="Số điện thoại chỉ 10 số")]
        public string Phone { get; set; }
        public string Full_Name { get; set; }
        public string Role { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
