//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XettuyenDGNLTHPT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XettuyenVLUEntities : DbContext
    {
        public XettuyenVLUEntities()
            : base("name=XettuyenVLUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblChungChiNN> tblChungChiNNs { get; set; }
        public virtual DbSet<tblDanToc> tblDanTocs { get; set; }
        public virtual DbSet<tblHoSoDGNL> tblHoSoDGNLs { get; set; }
        public virtual DbSet<tblHoSoTHPT> tblHoSoTHPTs { get; set; }
        public virtual DbSet<tblNganh> tblNganhs { get; set; }
        public virtual DbSet<tblQuocTich> tblQuocTiches { get; set; }
        public virtual DbSet<tblTinhTP> tblTinhTPs { get; set; }
        public virtual DbSet<tblTonGiao> tblTonGiaos { get; set; }
        public virtual DbSet<tblTruongTHPT> tblTruongTHPTs { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<tblTP_QH_PX> tblTP_QH_PX { get; set; }
    }
}
