//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XettuyenDGNLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChungChiNN
    {
        public int ID { get; set; }
        public string MaNN { get; set; }
        public string ChungChi { get; set; }
        public Nullable<double> DiemQuiDoi { get; set; }
    }
}
