//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XettuyenDGNLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoSoDGNL
    {
        public long ID { get; set; }
        public string HoVaTen { get; set; }
        public string Email { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string MaNoiSinh { get; set; }
        public string TenNoiSinh { get; set; }
        public string MaDanToc { get; set; }
        public string TenDanToc { get; set; }
        public string MaTonGiao { get; set; }
        public string TenTonGiao { get; set; }
        public string CMND { get; set; }
        public string QuocTich { get; set; }
        public string HoKhau { get; set; }
        public string HoKhau_MaPhuong { get; set; }
        public string HoKhau_TenPhuong { get; set; }
        public string HoKhau_MaTinhTP { get; set; }
        public string HoKhau_TenTinhTP { get; set; }
        public string HoKhau_MaQH { get; set; }
        public string HoKhau_TenQH { get; set; }
        public string NamTotNghiep { get; set; }
        public string SoBaoDanh { get; set; }
        public string HocLucLop12 { get; set; }
        public string HanhKiemLop12 { get; set; }
        public string LoaiHinhTN { get; set; }
        public string TruongTHPT_MaTinhTP { get; set; }
        public string TruongTHPT_TenTinhTP { get; set; }
        public string TruongTHPT_MaQH { get; set; }
        public string TruongTHPT_TenQH { get; set; }
        public string TenTruongTHPT { get; set; }
        public string MaTruongTHPT { get; set; }
        public string TenLop12 { get; set; }
        public string KhuVuc { get; set; }
        public Nullable<int> DiemDGNL { get; set; }
        public Nullable<System.DateTime> TGThiDGNL { get; set; }
        public string DoiTuongUuTien { get; set; }
        public string CCNN { get; set; }
        public string MaNganh_ToHop1 { get; set; }
        public string TenNganh_TenToHop1 { get; set; }
        public string CTDT1 { get; set; }
        public string MaNganh_ToHop2 { get; set; }
        public string TenNganh_TenToHop2 { get; set; }
        public string CTDT2 { get; set; }
        public string MaNganh_ToHop3 { get; set; }
        public string TenNganh_TenToHop3 { get; set; }
        public string CTDT3 { get; set; }
        public Nullable<int> CTCT { get; set; }
        public Nullable<int> CTDB { get; set; }
        public string LienLac_DiaChi { get; set; }
        public string LienLac_MaPhuongXa { get; set; }
        public string LienLac_TenPhuongXa { get; set; }
        public string LienLac_MaTP { get; set; }
        public string LienLac_TenTP { get; set; }
        public string LienLac_MaQH { get; set; }
        public string LienLac_TenQH { get; set; }
        public string DienThoaiDD { get; set; }
        public string DienThoaiPhuHuynh { get; set; }
        public Nullable<System.DateTime> DateInserted { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public string DaNhanHoSo { get; set; }
        public string DiemVeMyThuat { get; set; }
        public string DiemVeNangKhieu { get; set; }
        public string Dot { get; set; }
    }
}
