//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XettuyenDGNLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNganh
    {
        public int ID { get; set; }
        public string MANGANH_TOHOP { get; set; }
        public string MA_NGANH { get; set; }
        public string TEN_NGANH { get; set; }
        public string MA_TOHOP { get; set; }
        public string TEN_TOHOP { get; set; }
        public string CTTC { get; set; }
        public string CTDB { get; set; }
        public string CTTT { get; set; }
        public Nullable<bool> FLAG { get; set; }
    }
}
