//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XettuyenDGNLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTonGiao
    {
        public string MA_TONGIAO { get; set; }
        public string TEN_TONGIAO { get; set; }
        public string DIENGIAI { get; set; }
    }
}
