//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XettuyenDGNLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTP_QH_PX
    {
        public int ID { get; set; }
        public string TenTinhTP { get; set; }
        public string MaTinhTP { get; set; }
        public string TenQH { get; set; }
        public string MaQH { get; set; }
        public string TenPX { get; set; }
        public string MaPX { get; set; }
        public string Cap { get; set; }
        public string EnglishName { get; set; }
    }
}
