//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XettuyenDGNLTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTruongTHPT
    {
        public int ID { get; set; }
        public string MA_TPTRUONG { get; set; }
        public string MA_TINHTP { get; set; }
        public string TEN_TINHTP { get; set; }
        public string MA_QH { get; set; }
        public string TEN_QH { get; set; }
        public string MA_TRUONG { get; set; }
        public string TEN_TRUONG { get; set; }
        public string DIA_CHI { get; set; }
        public string KHU_VUC { get; set; }
        public string LOAI_TRUONG { get; set; }
    }
}
